### ISSUE TITLE
OMX Support for v4l2compress_h264

### ISSUE THREAD

**Issue by strfry** [mpromonet/v4l2tools#1]
Hello,

It would be nice for v4l2compress_h264 to support the hardware encoder of the Raspberry Pi.
I am developing a video streaming solution, which would benefit from increased performance and maybe lower latency.
Since the functionality is already there in v4l2grab_h264, it should be easy to combine those tools.

Best Regards,
Jonathan

**Comment by mpromonet** [comment]
Hi Jonahtan,
You are right, I already thought about it, it needs the time to do it...
Best Regards,
Michel.

**Comment by mpromonet** [comment]
Hi Jonahtan,
I just add a new tool `v4l2compress_omx` that capture using V4L2_PIX_FMT_YUV420 and compress in H264 using OMX compressor.
Regards
Michel.
