### ISSUE TITLE
Makefile:132: recipe for target 'h264bitstream/.libs/libh264bitstream.so' failed

### ISSUE THREAD

**Issue by Siggemada** [mpromonet/v4l2tools#13]
orangepiplus2e:~/v4l2tools$ sudo make
with log4cpp
git submodule update --init h264bitstream	
cd h264bitstream && autoreconf -i -f && ./configure --host arm-linux-gnueabihf
configure.ac:26: error: possibly undefined macro: AC_PROG_LD
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:28: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: /usr/bin/autoconf failed with exit status: 1
Makefile:132: recipe for target 'h264bitstream/.libs/libh264bitstream.so' failed
make: *** [h264bitstream/.libs/libh264bitstream.so] Error 1

What am I doing wrong?

**Comment by mpromonet** [comment]
Hi Siggemada,
Probably you are trying to use a too old autoconf.
MAybe you should try to cross-compile instead of compile on your target.
Best Regards,
Michel.

**Comment by Siggemada** [comment]
Hi, Its:
autoconf --version
autoconf (GNU Autoconf) 2.69
