### ISSUE TITLE
undefined reference to `MJPGSize'

### ISSUE THREAD

**Issue by Siggemada** [mpromonet/v4l2tools#15]
Wont build on H3:
v4l2tools/src/v4l2dump.cpp:135: undefined reference to `MJPGSize'
collect2: error: ld returned 1 exit status
Makefile:145: recipe for target 'v4l2dump' failed
make: *** [v4l2dump] Error 1

**Comment by dony71** [comment]
still problem

~/Download/v4l2tools# make
with log4cpp
g++ -o v4l2dump -W -Wall -pthread -g -pipe  -I include -DHAVE_LOG4CPP -I /usr/include -I v4l2wrapper/inc -DHAVE_JPEG src/v4l2dump.cpp libv4l2wrapper.a h264bitstream/.libs/libh264bitstream.so hevcbitstream/.libs/libhevcbitstream.so libyuv.a -llog4cpp  -ljpeg -Ih264bitstream  -Ihevcbitstream -Wl,-rpath=./h264bitstream/.libs,-rpath=./hevcbitstream/.libs -I libyuv/include
/tmp/ccmUg1Vs.o: In function `main':
/root/Download/v4l2tools/src/v4l2dump.cpp:136: undefined reference to `MJPGSize'
collect2: error: ld returned 1 exit status
Makefile:145: recipe for target 'v4l2dump' failed
make: *** [v4l2dump] Error 1
