### ISSUE TITLE
v4l2dump.cpp:136: undefined reference to `MJPGSize'

### ISSUE THREAD

**Issue by dmoralesdev** [mpromonet/v4l2tools#19]
Related to issue #15, but seems to be currently closed, so opening a new one for Dev's attention

/home/pi/v4l2tools/src/v4l2dump.cpp:136: undefined reference to `MJPGSize'
collect2: error: ld returned 1 exit status
Makefile:145: recipe for target 'v4l2dump' failed
make: *** [v4l2dump] Error 1

**Comment by mpromonet** [comment]
Hi,
Probably libyuv was build without JPEG support, did you check this ?
Best Regards,
Michel.
