### ISSUE TITLE
USB Easycap Video Grabber to v4l2loopback device using v4l2tools

### ISSUE THREAD

**Issue by mgoeller** [mpromonet/v4l2tools#20]
Hello, I want to use a analog video to USB grabber from logilink with the following capabilities on a Raspberry Pi:
![VG0001A png](https://user-images.githubusercontent.com/40425388/60817626-51bfb880-a19c-11e9-9ecf-8b2ba122704f.jpeg)

> v4l2-ctl --all -d /dev/video0
> Driver Info (not using libv4l2):
> 	Driver name   : uvcvideo
> 	Card type     : AV TO USB2.0
> 	Bus info      : usb-3f980000.usb-1.3
> 	Driver version: 4.14.98
> 	Capabilities  : 0x84200001
> 		Video Capture
> 		Streaming
> 		Extended Pix Format
> 		Device Capabilities
> 	Device Caps   : 0x04200001
> 		Video Capture
> 		Streaming
> 		Extended Pix Format
> Priority: 2
> Video input : 0 (Camera 1: ok)
> Format Video Capture:
> 	Width/Height      : 720/480
> 	Pixel Format      : 'YUYV'
> 	Field             : None
> 	Bytes per Line    : 1440
> 	Size Image        : 691200
> 	Colorspace        : Default
> 	Transfer Function : Default
> 	YCbCr/HSV Encoding: Default
> 	Quantization      : Default
> 	Flags             : 
> Crop Capability Video Capture:
> 	Bounds      : Left 0, Top 0, Width 720, Height 480
> 	Default     : Left 0, Top 0, Width 720, Height 480
> 	Pixel Aspect: 1/1
> Selection: crop_default, Left 0, Top 0, Width 720, Height 480
> Selection: crop_bounds, Left 0, Top 0, Width 720, Height 480
> Streaming Parameters Video Capture:
> 	Capabilities     : timeperframe
> 	Frames per second: 30.000 (30/1)
> 	Read buffers     : 0
>                      brightness (int)    : min=0 max=255 step=1 default=-8193 value=32
>                        contrast (int)    : min=0 max=255 step=1 default=57343 value=128
>                      saturation (int)    : min=0 max=255 step=1 default=57343 value=128
>                             hue (int)    : min=0 max=127 step=1 default=-8193 value=0
>                           gamma (int)    : min=0 max=50 step=1 default=57343 value=0

Optimal would be if the _v4l2compress_omx_ tool works with the YUYV pixel format of the USB grabber. I tried to adapt the source code and could compile, had however problems with the color space variable. So took a different approach and first copied the input from _/dev/video0_ using _v4l2convert_yuv_ to a v4l2loopback device _/dev/video2_, which works well so far:

> v4l2convert_yuv /dev/video0 /dev/video2 
> 2019-07-08 16:11:30,306 [NOTICE] - src/V4l2Device.cpp:117
> 	driver:uvcvideo capabilities:84200001 mandatory:4000001
> 2019-07-08 16:11:30,307 [NOTICE] - src/V4l2Device.cpp:120
> 	/dev/video0 support capture
> 2019-07-08 16:11:30,307 [NOTICE] - src/V4l2Device.cpp:123
> 	/dev/video0 support streaming
> 2019-07-08 16:11:30,307 [NOTICE] - src/V4l2Device.cpp:147
> 	/dev/video0:YUYV size:720x480
> 2019-07-08 16:11:30,315 [NOTICE] - src/V4l2MmapDevice.cpp:71
> 	Device /dev/video0 nb buffer:10
> 2019-07-08 16:11:30,319 [NOTICE] - src/V4l2Device.cpp:117
> 	driver:v4l2 loopback capabilities:85208003 mandatory:4000002
> 2019-07-08 16:11:30,319 [NOTICE] - src/V4l2Device.cpp:119
> 	/dev/video2 support output
> 2019-07-08 16:11:30,320 [NOTICE] - src/V4l2Device.cpp:120
> 	/dev/video2 support capture
> 2019-07-08 16:11:30,320 [NOTICE] - src/V4l2Device.cpp:122
> 	/dev/video2 support read/write
> 2019-07-08 16:11:30,320 [NOTICE] - src/V4l2Device.cpp:123
> 	/dev/video2 support streaming
> 2019-07-08 16:11:30,320 [NOTICE] - src/V4l2Device.cpp:147
> 	/dev/video2:BGR4 size:0x0
> 2019-07-08 16:11:30,321 [NOTICE] - src/V4l2Device.cpp:208
> 	/dev/video2:YU12 size:720x480 bufferSize:520192
> 2019-07-08 16:11:30,321 [NOTICE] - src/V4l2MmapDevice.cpp:71
> 	Device /dev/video2 nb buffer:8
> 2019-07-08 16:11:30,322 [NOTICE] - src/v4l2convert_yuv.cpp:136
> 	Start Copying from /dev/video0 to /dev/video2

Second step would be to use _v4l2compress_omx_ from _/dev/video2_ to _/dev/video1_, which returns me the following error:

> v4l2compress_omx -W 720 -H 480 /dev/video2 /dev/video1
> 2019-07-08 16:12:24,493 [NOTICE] - src/V4l2Device.cpp:117
> 	driver:v4l2 loopback capabilities:85208003 mandatory:4000001
> 2019-07-08 16:12:24,493 [NOTICE] - src/V4l2Device.cpp:119
> 	/dev/video2 support output
> 2019-07-08 16:12:24,493 [NOTICE] - src/V4l2Device.cpp:120
> 	/dev/video2 support capture
> 2019-07-08 16:12:24,493 [NOTICE] - src/V4l2Device.cpp:122
> 	/dev/video2 support read/write
> 2019-07-08 16:12:24,493 [NOTICE] - src/V4l2Device.cpp:123
> 	/dev/video2 support streaming
> 2019-07-08 16:12:24,493 [NOTICE] - src/V4l2Device.cpp:147
> 	/dev/video2:YU12 size:720x480
> 2019-07-08 16:12:24,493 [NOTICE] - src/V4l2Device.cpp:229
> 	fps:1/10
> 2019-07-08 16:12:24,493 [NOTICE] - src/V4l2Device.cpp:230
> 	nbBuffer:8
> 2019-07-08 16:12:24,493 [NOTICE] - src/V4l2MmapDevice.cpp:71
> 	Device /dev/video2 nb buffer:8
> 2019-07-08 16:12:24,494 [NOTICE] - src/V4l2Device.cpp:117
> 	driver:v4l2 loopback capabilities:85208003 mandatory:4000002
> 2019-07-08 16:12:24,494 [NOTICE] - src/V4l2Device.cpp:119
> 	/dev/video1 support output
> 2019-07-08 16:12:24,494 [NOTICE] - src/V4l2Device.cpp:120
> 	/dev/video1 support capture
> 2019-07-08 16:12:24,494 [NOTICE] - src/V4l2Device.cpp:122
> 	/dev/video1 support read/write
> 2019-07-08 16:12:24,494 [NOTICE] - src/V4l2Device.cpp:123
> 	/dev/video1 support streaming
> 2019-07-08 16:12:24,494 [NOTICE] - src/V4l2Device.cpp:147
> 	/dev/video1:BGR4 size:0x0
> 2019-07-08 16:12:24,495 [NOTICE] - src/V4l2Device.cpp:208
> 	/dev/video1:H264 size:720x480 bufferSize:1384448
> 2019-07-08 16:12:24,495 [NOTICE] - src/V4l2MmapDevice.cpp:71
> 	Device /dev/video1 nb buffer:8
> 2019-07-08 16:12:24,497 [NOTICE] - src/v4l2compress_omx.cpp:122
> 	Start Capturing from /dev/video2
> Port 200: in 1/1 15360 16 disabled,not pop.,not cont. 160x64 160x64 @1966080 20
> Port 200: in 1/1 15360 16 disabled,not pop.,not cont. 720x480 720x480 @1966080 20
> OMX_SetParameter(OMX_IndexParamVideoPortFormat) for video_encode:201...
> OMX_SetParameter(OMX_IndexParamBrcmVideoAVCInlineHeaderEnable) for video_encode:201...
> Current Bitrate=10000000
> encode to idle...
> enabling port buffers for 200...
> enabling port buffers for 201...
> encode to executing...
> 2019-07-08 16:12:24,505 [NOTICE] - src/v4l2compress_omx.cpp:138
> 	Start Compressing /dev/video2 to /dev/video1
> 2019-07-08 16:12:24,506 [WARN  ] - src/V4l2MmapDevice.cpp:191
> 	Device /dev/video2 buffer truncated available:518400 needed:520192
> 2019-07-08 16:12:24,536 [WARN  ] - src/V4l2MmapDevice.cpp:191
> 	Device /dev/video2 buffer truncated available:518400 needed:520192
> 2019-07-08 16:12:24,572 [WARN  ] - src/V4l2MmapDevice.cpp:191
> 	Device /dev/video2 buffer truncated available:518400 needed:520192
> 2019-07-08 16:12:24,604 [WARN  ] - src/V4l2MmapDevice.cpp:191
> 	Device /dev/video2 buffer truncated available:518400 needed:520192

I set the video ram on the raspberry pi to the maximum of 256 MB. Any idea what else I could try?

**Comment by mpromonet** [comment]
Hi mgoeller,
I don't think the problem is related to memory size, the capturer side of `v4l2compress_omx` reported buffer size for one frame is not big enough.
The stranger things is that the yuv converter says buffer size is 520192 and the compressor says 518400...
Did you try to use "write interface" to convert or "read interface" to compress ?
I need to dig a bit more in the mmap code, but there is some others users that complains about multiple instances.
Best Regards,
Michel.
