### ISSUE TITLE
problem building

### ISSUE THREAD

**Issue by sithdaddy** [mpromonet/v4l2tools#43]
what does this mean ?....

g++ -o v4l2source_yuv -std=c++11 -W -Wall -pthread -g -pipe  -I include -DHAVE_LOG4CPP  -I v4l2wrapper/inc -I /opt/vc/include/ -I /opt/vc/include/interface/vcos/ -I /opt/vc/include/interface/vcos/pthreads/ -I /opt/vc/include/interface/vmcs_host/linux/ -I /opt/vc/src/hello_pi/libs/ilclient  -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -DHAVE_LIBOPENMAX=2 -DOMX -DOMX_SKIP64BIT -ftree-vectorize -pipe -DUSE_EXTERNAL_OMX -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM -Wno-psabi -DHAVE_X264 -DHAVE_X265 -DHAVE_VPX -DHAVE_JPEG src/v4l2source_yuv.cpp libv4l2wrapper.a -llog4cpp  -L /opt/vc/lib -L /opt/vc/src/hello_pi/libs/ilclient -lpthread -lopenmaxil -lbcm_host -lvcos -lvchiq_arm -lx264 -lx265 -lvpx -ljpeg
cd h264bitstream && autoreconf -i -f && ./configure --host arm-linux-gnueabihf
**/bin/sh: 1: autoreconf: not found
make: *** [Makefile:142: h264bitstream/.libs/libh264bitstream.so] Error 127**

this happens when i do sudo make.

**Comment by mpromonet** [comment]
Hi,

This means you miss to install autoconf & automake. You could find the package to install from https://github.com/mpromonet/v4l2tools/blob/master/Dockerfile

Best Regards,
Michel.
