### ISSUE TITLE
Can't compile, missing AC_PROG_LIBTOOL

### ISSUE THREAD

**Issue by xNiux** [mpromonet/v4l2tools#44]
Hi,

When I tried to make it, the compilation break with "missing AC_PROG_LIBTOOL" :

![image](https://user-images.githubusercontent.com/25155398/149915743-055fbbe5-4cfa-4b2e-903e-dd55a3a35432.png)

It missing something ?

**Comment by mpromonet** [comment]
Hi @xNiux,

It seems libtool is missing, did you try to install `apt install autoconf automake libtool pkg-config` ?

Best Regards,
Michel

**Comment by xNiux** [comment]
Your right ! Thanks a lot !
